import {
  Activity,
  BarChart3,
  CheckCircle2,
  Cloud,
  CreditCard,
  Database,
  FileText,
  FlaskConical,
  Gauge,
  HardDrive,
  ListChecks,
  Mail,
  Monitor,
  Radio,
  Search,
  Server,
  Shield,
  Sparkles,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { TechCategory } from "@/lib/types";

export const categoryIcons: Record<TechCategory, LucideIcon> = {
  frontend: Monitor,
  backend: Server,
  database: Database,
  auth: Shield,
  storage: HardDrive,
  payments: CreditCard,
  ai: Sparkles,
  email: Mail,
  analytics: BarChart3,
  observability: Activity,
  cms: FileText,
  testing: FlaskConical,
  devops: Wrench,
  deployment: Cloud,
  search: Search,
  queue: ListChecks,
  cache: Gauge,
  realtime: Radio,
  validation: CheckCircle2,
};
