import {
  siAlgolia,
  siAngular,
  siAnthropic,
  siAstro,
  siAuth0,
  siBetterauth,
  siClerk,
  siCloudflare,
  siCloudinary,
  siContentful,
  siConvex,
  siCypress,
  siDatadog,
  siDigitalocean,
  siDocker,
  siDrizzle,
  siElasticsearch,
  siExpress,
  siFastify,
  siFirebase,
  siFlydotio,
  siFramer,
  siGithubpages,
  siGoogleanalytics,
  siGooglegemini,
  siHono,
  siJest,
  siLangchain,
  siLemonsqueezy,
  siLucia,
  siMailgun,
  siMeilisearch,
  siMinio,
  siMistralai,
  siMixpanel,
  siMongodb,
  siNeon,
  siNestjs,
  siNetlify,
  siNextdotjs,
  siNuxt,
  siNx,
  siOpentelemetry,
  siPaddle,
  siPayloadcms,
  siPaypal,
  siPlanetscale,
  siPlausibleanalytics,
  siPostgresql,
  siPosthog,
  siPrismic,
  siPrisma,
  siPusher,
  siRadixui,
  siRailway,
  siReact,
  siRedis,
  siRemix,
  siRender,
  siResend,
  siSanity,
  siSentry,
  siSocketdotio,
  siStoryblok,
  siStorybook,
  siStrapi,
  siStripe,
  siSupabase,
  siSvelte,
  siTailwindcss,
  siTemporal,
  siTestinglibrary,
  siThreedotjs,
  siTurborepo,
  siTurso,
  siUpstash,
  siVercel,
  siVite,
  siVitest,
  siVuedotjs,
  siZod,
  type SimpleIcon,
} from "./simple-icons-data";

const technologyLogoEntries: Array<[string, SimpleIcon]> = [
  ["AI SDK", siVercel],
  ["Algolia", siAlgolia],
  ["Angular", siAngular],
  ["Anthropic", siAnthropic],
  ["Astro", siAstro],
  ["Auth0", siAuth0],
  ["Better Auth", siBetterauth],
  ["Clerk", siClerk],
  ["Cloudflare", siCloudflare],
  ["Cloudinary", siCloudinary],
  ["Contentful", siContentful],
  ["Convex", siConvex],
  ["Cypress", siCypress],
  ["Datadog", siDatadog],
  ["DigitalOcean App Platform", siDigitalocean],
  ["Docker", siDocker],
  ["Drizzle", siDrizzle],
  ["Elasticsearch", siElasticsearch],
  ["Express", siExpress],
  ["Fastify", siFastify],
  ["Firebase", siFirebase],
  ["Firebase Hosting", siFirebase],
  ["Fly.io", siFlydotio],
  ["Framer Motion", siFramer],
  ["GitHub Pages", siGithubpages],
  ["Google AI", siGooglegemini],
  ["Google Analytics", siGoogleanalytics],
  ["Hono", siHono],
  ["Jest", siJest],
  ["LangChain", siLangchain],
  ["Lemon Squeezy", siLemonsqueezy],
  ["Lucia", siLucia],
  ["Mailgun", siMailgun],
  ["Meilisearch", siMeilisearch],
  ["Minio", siMinio],
  ["Mistral", siMistralai],
  ["Mixpanel", siMixpanel],
  ["MongoDB", siMongodb],
  ["Neon", siNeon],
  ["NestJS", siNestjs],
  ["Netlify", siNetlify],
  ["Next.js", siNextdotjs],
  ["Nuxt", siNuxt],
  ["Nx", siNx],
  ["OpenTelemetry", siOpentelemetry],
  ["Paddle", siPaddle],
  ["Payload", siPayloadcms],
  ["PayPal", siPaypal],
  ["PlanetScale", siPlanetscale],
  ["Plausible", siPlausibleanalytics],
  ["PostgreSQL", siPostgresql],
  ["PostHog", siPosthog],
  ["Prismic", siPrismic],
  ["Prisma", siPrisma],
  ["Pusher", siPusher],
  ["Radix UI", siRadixui],
  ["Railway", siRailway],
  ["React", siReact],
  ["React Native", siReact],
  ["Redis", siRedis],
  ["Remix", siRemix],
  ["Render", siRender],
  ["Resend", siResend],
  ["Sanity", siSanity],
  ["Sentry", siSentry],
  ["Socket.IO", siSocketdotio],
  ["Storyblok", siStoryblok],
  ["Storybook", siStorybook],
  ["Strapi", siStrapi],
  ["Stripe", siStripe],
  ["Supabase", siSupabase],
  ["Supabase Auth", siSupabase],
  ["Svelte", siSvelte],
  ["Tailwind", siTailwindcss],
  ["Temporal", siTemporal],
  ["Testing Library", siTestinglibrary],
  ["Three.js", siThreedotjs],
  ["Turborepo", siTurborepo],
  ["Turso", siTurso],
  ["Upstash QStash", siUpstash],
  ["Vercel", siVercel],
  ["Vercel Analytics", siVercel],
  ["Vercel Blob", siVercel],
  ["Vite", siVite],
  ["Vitest", siVitest],
  ["Vue", siVuedotjs],
  ["Zod", siZod],
];

const technologyLogos = new Map<string, SimpleIcon>(
  technologyLogoEntries.map(([name, icon]) => [normalizeTechnologyName(name), icon])
);

export function getTechnologyLogo(name: string) {
  return technologyLogos.get(normalizeTechnologyName(name));
}

function normalizeTechnologyName(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "");
}
